[server]
maxUploadSize = 200
headless = true
 
[theme]
base = "dark"
backgroundColor = "#0a0f1e"
secondaryBackgroundColor = "#0f172a"
primaryColor = "#008751"
textColor = "#e2e8f0"
font = "sans serif"
